### ISSUE TITLE
Possibly add an example project to showcase use of the library?

### ISSUE THREAD

**Issue by gurs1kh** [joelmukuthu/knorm#62]
Though this library does look promising, I'm finding it difficult to get started.
I think it would be a good if there was an example project to show how it works and to act as a boilerplate for those wanting to use it.

**Comment by joelmukuthu** [comment]
Hi! Thanks for the feedback, I created an example repo here https://github.com/joelmukuthu/knorm-example. I mostly re-used stuff from the [Knorm docs](https://joelmukuthu.github.io/knorm/#/) but I can see they do need to be improved, perhaps as a step-by-step guide, do you think that would have helped?

**Comment by gurs1kh** [comment]
Yeah, a guide would be very helpful.

**Comment by joelmukuthu** [comment]
I agree. I have quite a lot in the pipeline for knorm, that I'm afraid this is lower in my priority. Would you like to take a shot at re-structuring the getting-started guides so they're more useful? I will of course be available to help out if needed :)

**Comment by joelmukuthu** [comment]
Closing with deference to #66

**Comment by gurs1kh** [comment]
Sorry for the late reply. Anyways, I had difficulty getting started myself, so I don't think I'd be the best to make a guide :).
